version: "3.1"

services:

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=smart
      - MONGO_INITDB_ROOT_PASSWORD=smartcode

  mongoexpress:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=smart
      - ME_CONFIG_MONGODB_ADMINPASSWORD=smartcode
      - ME_CONFIG_MONGODB_SERVER=mongodb

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://smart:smartcode@mongodb:27017/mydb
